#ifndef CONFIG_H
#define CONFIG_H

/* Define INDI Data Dir */
#cmakedefine INDI_DATA_DIR "@INDI_DATA_DIR@"

/* Define Driver version */
#define ARDST4GOTO_VERSION_MAJOR @ARDST4GOTO_VERSION_MAJOR@
#define ARDST4GOTO_VERSION_MINOR @ARDST4GOTO_VERSION_MINOR@

#endif // CONFIG_H
